#include "testspi.h"

TEST_GROUP(spi);

TEST_SETUP(spi)
{
	
}

TEST_TEAR_DOWN(spi)
{
}

/* Tests */
TEST(spi, ControlRegisterConstants)
{
	TEST_ASSERT_EQUAL_HEX8(0, SPR0);
	TEST_ASSERT_EQUAL_HEX8(1, SPR1);
	TEST_ASSERT_EQUAL_HEX8(2, CPHA);
	TEST_ASSERT_EQUAL_HEX8(3, CPOL);
	TEST_ASSERT_EQUAL_HEX8(4, MSTR);
	TEST_ASSERT_EQUAL_HEX8(5, DORD);
	TEST_ASSERT_EQUAL_HEX8(6, SPE);
	TEST_ASSERT_EQUAL_HEX8(7, SPIE);
}

TEST_GROUP_RUNNER(spi)
{ 
	RUN_TEST_CASE(spi, ControlRegisterConstants);
}

